apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: 4taku-direboar

#DB settings are different in the development environment, so fix.
configMapGenerator:
  - name: database-config
    behavior: merge
    literals:
      - db-server-name=postgres-postgresql-hl.database-direboar
      - db-server-port=5432
      - db-name=postgres
      - db-user-name=postgres
#If configMapGenerator sets Hash to name, there is a problem that Hash is not set on the Deployment side, so we have chosen not to set Hash.
generatorOptions:
  disableNameSuffixHash: true

#DB settings are different in the development environment, so fix.
secretGenerator:
  - name: database-secrets
    behavior: merge
    literals:
      - "db-password=changeme"

#In the development environment, schedule is modified to be set to run every minute.
patchesJson6902:
  - path: ./patch-get-minder-ranking.yaml
    target:
      group: batch
      version: v1
      kind: CronJob
      name: 4taku-batch.get-minder-ranking
  - path: ./patch-update-hero.yaml
    target:
      group: batch
      version: v1
      kind: CronJob
      name: 4taku-batch.update-hero
  - path: ./patch-database-secrets.yaml
    target:
      version: v1
      kind: Secret
      name: database-secrets  

images:
- name: minokuba/4taku-api
  newName: minokuba/4taku-api
  newTag: develop
- name: minokuba/4taku-batch
  newName: minokuba/4taku-batch
  newTag: develop1
