apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: 4taku-staging-direboar

#Set up replication
replicas:
  - name: 4taku-api
    count: 2

configMapGenerator:
- name: database-config
  behavior: merge
  literals:
      - db-server-name=postgres-postgresql-hl.testdatabase-direboar
