apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: 4taku-staging
replicas:
  - name: 4taku-api
    count: 3
configMapGenerator:
- name: database-config
  behavior: merge
  literals:
      - db-server-name=postgres-postgresql-hl.stg-database-direboar
