apiVersion: apps/v1
kind: Deployment
metadata:
  name: 4taku-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: 4taku-api
  template:
    metadata:
      labels:
        app: 4taku-api
    spec:
      containers:
        - name: 4taku-api
          image: minokuba/4taku-api
          env:
            - name: db-server-name
              valueFrom:
                configMapKeyRef:
                  key: db-server-name
                  name: database-config
            - name: db-server-port
              valueFrom:
                configMapKeyRef:
                  key: db-server-port
                  name: database-config
            - name: db-name
              valueFrom:
                configMapKeyRef:
                  key: db-name
                  name: database-config
            - name: db-username
              valueFrom:
                configMapKeyRef:
                  key: db-user-name
                  name: database-config
            - name: db-password
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: database-secrets
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: AUTH0_CLIENT_ID
                  name: auth0-secrets
            - name: AUTH0_AUTH_SERVER_URL
              valueFrom:
                secretKeyRef:
                  key: AUTH0_AUTH_SERVER_URL
                  name: auth0-secrets
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  key: AUTH0_AUDIENCE
                  name: auth0-secrets
            - name: OICD_BATTLENET_TOKEN_PATH
              valueFrom:
                secretKeyRef:
                  key: OICD_BATTLENET_TOKEN_PATH
                  name: oicd-secrets
            - name: OICD_BATTLENET_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: OICD_BATTLENET_CLIENT_ID
                  name: oicd-secrets
            - name: OICD_BATTLENET_SECRET
              valueFrom:
                secretKeyRef:
                  key: OICD_BATTLENET_SECRET
                  name: oicd-secrets
          imagePullPolicy: IfNotPresent #If the image has already been retrieved from the registry, do not reacquire it.
          resources:
            #It appears that okteto sees per-pod limits, but does not check per-namespace limits.
            requests:
              memory: 2000Mi
              cpu: 1000m
            limits:
              memory: 2000Mi
              cpu: 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: service-4taku-api
  labels:
    app: service-4taku-api
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    app: 4taku-api
