apiVersion: batch/v1
kind: CronJob
metadata:
  name: 4taku-batch.get-minder-ranking
spec:
  schedule: "0 15 * * *" #Starts at 0:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: 4taku-batch-get-minder-ranking
              image: minokuba/4taku-batch
              imagePullPolicy: IfNotPresent #If the image has already been retrieved from the registry, do not reacquire it.
              args:
                - "get-minder-ranking"
              env:
                - name: db-server-name
                  valueFrom:
                    configMapKeyRef:
                      key: db-server-name
                      name: database-config
                - name: db-server-port
                  valueFrom:
                    configMapKeyRef:
                      key: db-server-port
                      name: database-config
                - name: db-name
                  valueFrom:
                    configMapKeyRef:
                      key: db-name
                      name: database-config
                - name: db-username
                  valueFrom:
                    configMapKeyRef:
                      key: db-user-name
                      name: database-config
                - name: db-password
                  valueFrom:
                    secretKeyRef:
                      key: db-password
                      name: database-secrets
              resources:
                #It appears that okteto sees per-pod limits, but does not check per-namespace limits.
                requests:
                  memory: 2000Mi
                  cpu: 1000m
                limits:
                  memory: 2000Mi
                  cpu: 1000m
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: 4taku-batch.update-hero
spec:
  schedule: "0 16 * * *" #Starts at 1:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: 4taku-batch-update-hero
              image: minokuba/4taku-batch
              imagePullPolicy: IfNotPresent #If the image has already been retrieved from the registry, do not reacquire it.
              args:
                - "update-hero"
              env:
                - name: db-server-name
                  valueFrom:
                    configMapKeyRef:
                      key: db-server-name
                      name: database-config
                - name: db-server-port
                  valueFrom:
                    configMapKeyRef:
                      key: db-server-port
                      name: database-config
                - name: db-name
                  valueFrom:
                    configMapKeyRef:
                      key: db-name
                      name: database-config
                - name: db-username
                  valueFrom:
                    configMapKeyRef:
                      key: db-user-name
                      name: database-config
                - name: db-password
                  valueFrom:
                    secretKeyRef:
                      key: db-password
                      name: database-secrets
                - name: OICD_BATTLENET_TOKEN_PATH
                  valueFrom:
                    secretKeyRef:
                      key: OICD_BATTLENET_TOKEN_PATH
                      name: oicd-secrets
                - name: OICD_BATTLENET_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: OICD_BATTLENET_CLIENT_ID
                      name: oicd-secrets
                - name: OICD_BATTLENET_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: OICD_BATTLENET_SECRET
                      name: oicd-secrets
              resources:
                #It appears that okteto sees per-pod limits, but does not check per-namespace limits.
                requests:
                  memory: 2000Mi
                  cpu: 1000m
                limits:
                  memory: 2000Mi
                  cpu: 1000m
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: 4taku-batch.migrate-flyway
spec:
  template:
    spec:
      containers:
        - name: 4taku-batch-migrate-flyway
          image: minokuba/4taku-batch
          imagePullPolicy: IfNotPresent #If the image has already been retrieved from the registry, do not reacquire it.
          args:
            - "migrate-flyway"
#             - "-cl"
          env:
            - name: db-server-name
              valueFrom:
                configMapKeyRef:
                  key: db-server-name
                  name: database-config
            - name: db-server-port
              valueFrom:
                configMapKeyRef:
                  key: db-server-port
                  name: database-config
            - name: db-name
              valueFrom:
                configMapKeyRef:
                  key: db-name
                  name: database-config
            - name: db-username
              valueFrom:
                configMapKeyRef:
                  key: db-user-name
                  name: database-config
            - name: db-password
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: database-secrets
          resources:
            #It appears that okteto sees per-pod limits, but does not check per-namespace limits.
            requests:
              memory: 2000Mi
              cpu: 1000m
            limits:
              memory: 2000Mi
              cpu: 1000m
      restartPolicy: OnFailure
