apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-api.yaml
- deployment-batch.yaml
- database-secrets.yaml

configMapGenerator:
- literals:
  - db-server-name=postgres-postgresql-hl.database-direboar
  - db-server-port=5432
  - db-name=4taku
  - db-user-name=4taku-user
  name: database-config
generatorOptions:
  disableNameSuffixHash: true

images:
- name: minokuba/4taku-api
  newName: minokuba/4taku-api
  newTag: 915630cd3e98e6b56ac682297b84484028070791
- name: minokuba/4taku-batch
  newName: minokuba/4taku-batch
  newTag: 915630cd3e98e6b56ac682297b84484028070791
