apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-api.yaml
- deployment-batch.yaml
- database-secrets.yaml

configMapGenerator:
- literals:
  - db-server-name=postgres-postgresql-hl.database-direboar
  - db-server-port=5432
  - db-name=4taku
  - db-user-name=4taku-user
  name: database-config
generatorOptions:
  disableNameSuffixHash: true

images:
- name: minokuba/4taku-api
  newName: minokuba/4taku-api
  newTag: d59cd9dfcb939ec9d4ad931d08a71383bb6407ef
- name: minokuba/4taku-batch
  newName: minokuba/4taku-batch
  newTag: d59cd9dfcb939ec9d4ad931d08a71383bb6407ef
