apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-api.yaml
- deployment-batch.yaml

# namespace: 4taku-direboar

configMapGenerator:
- literals:
  - db-server-name=postgres-postgresql-hl.database-direboar
  - db-server-port=5432
  - db-name=4taku
  - db-user-name=4taku-user
  name: database-config
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- literals:
  - db-password=4taku-pass
  name: database-secrets
images:
- name: minokuba/4taku-api
  newName: minokuba/4taku-api
  newTag: 6e2c8739927d116d73531b55b82edbf89a67be2e
- name: minokuba/4taku-batch
  newName: minokuba/4taku-batch
  newTag: 6e2c8739927d116d73531b55b82edbf89a67be2e
