apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-api.yaml
- deployment-batch.yaml
- database-secrets.yaml
- auth0-secrets.yaml
- oicd-secrets.yaml

configMapGenerator:
- literals:
  - db-server-name=postgres-postgresql-hl.database-direboar
  - db-server-port=5432
  - db-name=4taku
  - db-user-name=4taku-user
  name: database-config
generatorOptions:
  disableNameSuffixHash: true

images:
- name: minokuba/4taku-api
  newName: minokuba/4taku-api
  newTag: 8ed648bba62d03500f023c7d595197fbd11df6ee
- name: minokuba/4taku-batch
  newName: minokuba/4taku-batch
  newTag: 8ed648bba62d03500f023c7d595197fbd11df6ee
