# file: .github/workflows/deploy-octeto-prod.yaml
name: deploy-octeto-prod

on:
  pull_request:
    types:
      - closed
    branches:    
      - 'master'
  workflow_dispatch:

jobs:
  deploy-octeto:
    if: github.event.pull_request.merged == true  
    runs-on: ubuntu-latest

    steps:
    # - name: Context
    #   uses: okteto/context@latest
    #   with:
    #     token: ${{ secrets.OKTETO_TOKEN }}
    - name: Checkout manifest repository
      uses: actions/checkout@v2

    - name: Set up Kubesec
      run: |
        curl -sSL https://github.com/shyiko/kubesec/releases/download/0.9.2/kubesec-0.9.2-linux-amd64 \
        -o kubesec && chmod a+x kubesec && sudo mv kubesec /usr/local/bin/

    - name: decrypt 
      run: |
         kubesec decrypt -i base/database-secrets.yaml.secrets -o base/database-secrets.yaml

    - name: deploy app by kubectl
      uses: actions-hub/kubectl@master
      env:
        KUBECONFIG : ${{ secrets.KUBECONFIG  }} 
    # pullrequestブランチの内容をクラスタに反映するので要注意。
    # okteto/pipelineはBranchを指定できないので、この挙動を変えるには、
    # on:
    #   push:
    #     branches:
    #       - main
    # をトリガーに動かさないとだめそう。
    # - name: "Trigger the pipeline"
    #   uses: okteto/pipeline@latest
    #   with:
    #     name: pipeline
    #     timeout: 8m
    #     skipIfExists: false # これにしておくとmanifestを再読込してくれる
    #     namespace : 4taku-direboar
    #     filename : ./okteto/deploy-octeto-prod-pipeline.yml
