name: update manifest production

on:
  workflow_dispatch:
  # repository_dispatch:
  #   types: [update-manifest-production]

jobs:
  update-manifests:
    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
      - name: Checkout manifest repository
        uses: actions/checkout@v2
        with : 
          ref: main
          # ref: production

      # kustomizeのインストール
      - name: Install kustomize
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl
          sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl

      # `kustomize edit set image`コマンドで、使用するイメージのタグを更新
      # その際に使用するタグは、repository-dispatch経由で受け取ったコミットハッシュを使用
      - name: Update image tag
        run: |
          cd base
          /usr/local/bin/kustomize edit set image minokuba/4taku-api=minokuba/4taku-api:xxx
          /usr/local/bin/kustomize edit set image minokuba/4taku-batch=minokuba/4taku-batch:xx
          cd -

      # 使用するイメージのタグを更新し、Pull Requestの作成
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "main"                                 # If blank, default: triggered branch
          destination_branch: "production"                      # If blank, default: master
          pr_title: "Update manifest xx" # Title of pull request
          pr_body: ":xxx"              # Full markdown support, requires pr_title to be set
          # pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
          # pr_reviewer: "wei,worker"                         # Comma-separated list (no spaces)
          # pr_assignee: "wei,worker"                         # Comma-separated list (no spaces)
          # pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          # pr_milestone: "Milestone 1"                       # Milestone name
          pr_draft: true                                    # Creates pull request as draft
          # pr_allow_empty: true                              # Creates pull request even if there are no changes
          github_token: ${{ secrets.GITHUB_TOKEN }}
        #         uses: peter-evans/create-pull-request@v3.8.2
        # with:
        #   commit-message: "Update manifest"
        #   title: Update manifest ${{ github.event.client_payload.sha }}
        #   body: ""
        #   labels: ""
        #   branch: update-manifest-${{ github.event.client_payload.sha }}
        #   base: production
